### ISSUE TITLE
Unit dev test error

### ISSUE THREAD

**Issue by liangjiangliang** [davyam/pgEasyReplication#2]
when I run the testUnit there is an error
postgresql is 11.6 , plug is test_coding

org.postgresql.util.PSQLException: ERROR: option "proto_version" = "1" is unknown
  在位置：slot "test_slot", output plugin "test_decoding", in the startup callback
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2505)
	at org.postgresql.core.v3.QueryExecutorImpl.processCopyResults(QueryExecutorImpl.java:1165)
	at org.postgresql.core.v3.QueryExecutorImpl.startCopy(QueryExecutorImpl.java:881)
	at org.postgresql.core.v3.replication.V3ReplicationProtocol.initializeReplication(V3ReplicationProtocol.java:58)
	at org.postgresql.core.v3.replication.V3ReplicationProtocol.startLogical(V3ReplicationProtocol.java:42)
	at org.postgresql.replication.fluent.ReplicationStreamBuilder$1.start(ReplicationStreamBuilder.java:38)
	at org.postgresql.replication.fluent.logical.LogicalStreamBuilder.start(LogicalStreamBuilder.java:37)
	at com.dg.easyReplication.Stream.<init>(Stream.java:36)
	at com.dg.easyReplication.PGEasyReplication.readEvent(PGEasyReplication.java:117)
	at com.dg.easyReplication.UnitTest.main(UnitTest.java:81)
Exception in thread "main" java.lang.NullPointerException
	at com.dg.easyReplication.UnitTest.main(UnitTest.java:82)

**Comment by davyam** [comment]
Hi @liangjiangliang, 

Thanks for the information, I'll check this error in the UnitTest.java.

**Comment by davyam** [comment]
@liangjiangliang,

You are getting this error because you change the logical decoding output plugin.

The test_coding plugin doesn't recognize the options that we set in the replication slot (see lines 33 and 34 at Stream.java).

The pgEasyReplication was build to use pgoutput plugin only (see line 67 at PGEasyReplication.java).

More details about pgoutput options: https://github.com/postgres/postgres/blob/master/src/backend/replication/pgoutput/pgoutput.c

**Comment by liangjiangliang** [comment]
Thank you very much for answering my question.
